=== bengtmartensson/dispatcher/src/main/resources/schemas/event-action-map.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="unqualified">

    <!--xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/-->

    <xs:element name="event-action-map">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" ref="action-templates" />
                <xs:element minOccurs="1" maxOccurs="1" ref="ir-commands" />
            </xs:sequence>
            <xs:attribute name="version" fixed="0.0.1" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Version of the schema the document claims to follow.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="action-templates">
         <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="action-template" />
            </xs:sequence>
         </xs:complexType>
    </xs:element>

    <xs:element name="parameters">
         <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="parameter" />
            </xs:sequence>
         </xs:complexType>
    </xs:element>

    <xs:element name="parameter">
        <xs:complexType>
            <xs:attribute name="description" type="xs:string"/>
            <xs:attribute name="default" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="action-template">
         <xs:complexType>
            <xs:sequence minOccurs="1">
                <xs:element minOccurs="0" maxOccurs="1" ref="parameters" />
                <xs:element minOccurs="1" maxOccurs="1" ref="action" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
         </xs:complexType>
    </xs:element>

    <xs:element name="ir-commands">
         <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="ir-command" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
         </xs:complexType>
    </xs:element>

    <xs:element name="ir-command">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:choice>
                    <xs:element ref="actionref" />
                    <xs:element ref="action" />
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="protocol" type="xs:NMTOKEN" use="required" />
            <xs:attribute name="D" type="xs:nonNegativeInteger" use="required" />
            <xs:attribute name="S" type="xs:nonNegativeInteger" />
            <xs:attribute name="F" type="xs:nonNegativeInteger" use="required" />
            <xs:attribute default="1" name="min" type="xs:nonNegativeInteger" />
            <xs:attribute default="9999" name="max" type="xs:nonNegativeInteger" />
            <xs:attribute name="remote" type="xs:string" />
            <xs:attribute name="commandName" type="xs:string" />
            <xs:attribute name="description" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="actionref">
        <xs:complexType>
            <xs:attribute name="template" type="xs:IDREF" use="required" />
            <xs:attribute name="arg1" type="xs:string"/>
            <xs:attribute name="arg2" type="xs:string"/>
        </xs:complexType>
    </xs:element>

  <xs:element name="action">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="echo" />
        <xs:element ref="quit" />
        <xs:element ref="restart" />
        <xs:element ref="exec" />
        <xs:element ref="wol" />
        <xs:element ref="tcp" />
        <xs:element ref="udp" />
        <xs:element ref="http" />
        <xs:element ref="homeassistant" />
      </xs:choice>
      <xs:attribute default="1" name="min" type="xs:nonNegativeInteger" />
      <xs:attribute default="9999" name="max" type="xs:nonNegativeInteger" />
      <xs:attribute name="description" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="homeassistant">
      <xs:complexType>
          <xs:attribute name="host" type="xs:string" default="homeassistant"/>
          <xs:attribute name="port" type="xs:nonNegativeInteger" default="8123"/>
          <xs:attribute name="token" type="xs:string" default="@token.txt"/>
          <xs:attribute name="type" default="put">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:enumeration value="get"/>
                      <xs:enumeration value="put"/>
                  </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="kind" default="services">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:enumeration value="services"/>
                      <xs:enumeration value="events"/>
                  </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="domain">
              <xs:simpleType>
                  <xs:restriction base="xs:string">
                      <xs:enumeration value="homeassistant"/>
                      <xs:enumeration value="light"/>
                      <xs:enumeration value="switch"/>
                      <xs:enumeration value="shell_command"/>
                  </xs:restriction>
              </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="service" type="xs:string" use="optional"/>
          <xs:attribute name="entity_id" type="xs:string" use="optional"/>
      </xs:complexType>
  </xs:element>

  <xs:element name="echo" type="xs:string" />

  <xs:element name="quit">
    <xs:complexType />
  </xs:element>

  <xs:element name="restart">
    <xs:complexType />
  </xs:element>

  <xs:element name="wol">
    <xs:complexType>
      <!-- one of these -->
      <xs:attribute name="mac" type="xs:string" />
      <xs:attribute name="hostname" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="tcp">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="hostname" type="xs:NMTOKEN" use="required" />
          <xs:attribute name="port" type="portNumberType" use="required" />
          <xs:attribute default="2000" name="timeout" type="xs:nonNegativeInteger" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="udp">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="hostname" type="xs:NMTOKEN" use="required" />
          <xs:attribute name="port" type="portNumberType" use="required" />
          <xs:attribute default="2000" name="timeout" type="xs:nonNegativeInteger" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="http">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="url" type="xs:string" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="exec">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="argument" />
      </xs:sequence>
      <xs:attribute name="progname" type="xs:string" use="required" />
      <xs:attribute default="true" name="wait" type="xs:boolean"/>
        <!--xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute-->
      <xs:attribute name="in" type="xs:string" />
      <xs:attribute name="out" type="xs:string" />
      <xs:attribute name="err" type="xs:string" />
      <xs:attribute name="directory" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:element name="argument" type="xs:string" />

  <xs:simpleType name="portNumberType">
        <xs:annotation>
            <xs:documentation>Number between 0 and 65535.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="65535"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== bengtmartensson/dispatcher/src/main/config/listener.xml
<?xml version="1.0" encoding="UTF-8"?>
<event-action-map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.0.1" xsi:noNamespaceSchemaLocation="../schemas/event-action-map.xsd">
    <action-templates>

        <action-template id="ezcontrol-predefined-http">
            <parameters>
                <parameter description="predefined switch number"/>
                <parameter description="on or off" default="on"/>
            </parameters>
            <action min="2">
                <http url="http://ezcontrol/preset?switch=$1&amp;value=$2"/>
            </action>
        </action-template>

        <action-template id="harcmacro">
            <parameters>
                <parameter description="command string to send"/>
            </parameters>
            <action min="2">
                <udp hostname="harc" port="9998" timeout="1000">harcmacros.$1</udp>
            </action>
        </action-template>

    </action-templates>


    <ir-commands>
        <!--
        <ir-command protocol="NEC1" D="73" F="83" description="OK for Oppo">
            <action min="6">
                <echo>Hey mama, got OK from Oppo</echo>
                <tcp hostname="localhost" port="44444" timeout="1000">Ok from Oppo</tcp>
            </action>
            <action min="1" max="5">
                <log>Logg mama, got OK from Oppo</log>
            </action>
        </ir-command>
        <ir-command protocol="NEC1" D="73" F="71" remote="Oppo"
                    commandName="A" description="">
            <action min = "5" description="">
                <quit/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="0" F="0">
            <action>
                <echo>Got rc5 0 0</echo>
                <udp hostname="irtrans" port="21000" timeout="2000">sndccf 0000 0073 0000 000D 0020 0020 0040 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0020 0CC8,li</udp>
            </action>
        </ir-command>


        <ir-command protocol="rc5" D="5" F="1">
            <action>
                <exec progname="/usr/bin/wc" in="/etc/passwd" wait="true"/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="5" F="2">
            <action>
                <exec progname="ls" wait="false" out="/tmp/junk"/>
            </action>
            <action min="5">
                <exec progname="ls" wait="false" directory="/etc"/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="5" F="3">
            <action>
                <exec progname="cat" wait="true" err="/tmp/junk">
                    <argument>/etc/shadow</argument>
                </exec>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="5" F="4">
            <action>
                <http url="http://ezcontrol/send?system=6&amp;hc1=13&amp;hc2=3&amp;addr=2&amp;value=255"/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="5" F="5">
            <action>
                <http url="http://ezcontrol/send?system=6&amp;hc1=13&amp;hc2=3&amp;addr=2&amp;value=0"/>
            </action>
        </ir-command>
-->
        <!-- WOL commands -->
        <ir-command protocol="rc5" D="31" F="999">
            <action>
                <wol mac="00:00:00:00:00:00"/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <action>
                <wol hostname="box"/>
            </action>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <action>
                <wol hostname="epsilon"/>
            </action>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="90">
            <actionref template="harcmacro" arg1="start_dbox_tv()"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="91">
            <actionref template="harcmacro" arg1="bedtime()"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="24">
            <actionref template="harcmacro" arg1="door_open_close()"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="92">
            <actionref template="harcmacro" arg1="leaving_home()"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="93">
            <actionref template="harcmacro" arg1="movie()"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="94">
            <actionref template="harcmacro" arg1="tv_mode(True)"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="95">
            <actionref template="harcmacro" arg1="all_up()"/>
        </ir-command>

        <!-- Ezcontrol T-10 preprogrammed commands -->
        <!-- Use F="999" for unassigned -->
        <ir-command protocol="rc5" D="31" F="999" description="Floorlamp_1">
            <!-- preset_1 -->
            <actionref template="ezcontrol-predefined-http" arg1="1" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999" description="Floorlamp_1">
            <!-- preset_1 -->
            <actionref template="ezcontrol-predefined-http" arg1="1" arg2="on"/>
        </ir-command>

        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_1 -->
            <!-- Floorlamp_1 -->
            <actionref template="ezcontrol-predefined-http" arg1="1" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_1 -->
            <!-- Floorlamp_1 -->
            <actionref template="ezcontrol-predefined-http" arg1="1" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_2 -->
            <!-- Floorlamp_2 -->
            <actionref template="ezcontrol-predefined-http" arg1="2" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_2 -->
            <!-- Floorlamp_2 -->
            <actionref template="ezcontrol-predefined-http" arg1="2" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_3 -->            <!-- Floorlamp_3 -->
            <actionref template="ezcontrol-predefined-http" arg1="3" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_3 -->
            <!-- Floorlamp_3 -->
            <actionref template="ezcontrol-predefined-http" arg1="3" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="35">
            <!-- preset_4 -->
            <!-- Screen -->            <!--action min="2">
                <actionref template="ezcontrol-predefined-http" arg1="4" arg2="off"/>
            </action-->
            <actionref template="ezcontrol-predefined-http" arg1="4" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="3">
            <!-- preset_4 -->
            <!-- Screen -->
            <actionref template="ezcontrol-predefined-http" arg1="4" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_5 -->
            <!-- work_light -->
            <actionref template="ezcontrol-predefined-http" arg1="5" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_5 -->
            <!-- work_light -->
            <actionref template="ezcontrol-predefined-http" arg1="5" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_6 -->
            <!-- water&amp -->
            <actionref template="ezcontrol-predefined-http" arg1="6" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_6 -->
            <!-- water&amp -->
            <actionref template="ezcontrol-predefined-http" arg1="6" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_7 -->
            <!-- water_lamp -->
            <actionref template="ezcontrol-predefined-http" arg1="7" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_7 -->
            <!-- water_lamp -->
            <actionref template="ezcontrol-predefined-http" arg1="7" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_8 -->
            <!-- water_wall -->
            <actionref template="ezcontrol-predefined-http" arg1="8" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="999">
            <!-- preset_8 -->
            <!-- water_wall -->
            <actionref template="ezcontrol-predefined-http" arg1="8" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="40">
            <!-- preset_9" -->
            <!-- large_blind -->
            <actionref template="ezcontrol-predefined-http" arg1="9" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="8">
            <!-- preset_9 -->
            <!-- large_blind -->
            <actionref template="ezcontrol-predefined-http" arg1="9" arg2="on"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="41">
            <!-- preset_10" number="10" state="on">small_blind" arg2="off"/-->
            <actionref template="ezcontrol-predefined-http" arg1="10" arg2="off"/>
        </ir-command>
        <ir-command protocol="rc5" D="31" F="9">
            <!-- preset_10" number="10" state="on">small_blind" arg2="off"/-->
            <actionref template="ezcontrol-predefined-http" arg1="10" arg2="on"/>
        </ir-command>
        <!-- preset_11" number -->
        <ir-command protocol="rc5" D="31" F="42">
            <actionref template="ezcontrol-predefined-http" arg1="11" arg2="off"/>
            <!-- balcony_blind -->
        </ir-command>
        <!-- preset_11" number -->
